#ifndef PLUGIN_MANAGER_GLOBAL_H
#define PLUGIN_MANAGER_GLOBAL_H

#if defined(PLUGIN_SYSTEM_LIBRARY)
#  define PLUGIN_SYSTEM_EXPORT Q_DECL_EXPORT
#else
#  define PLUGIN_SYSTEM_EXPORT Q_DECL_IMPORT
#endif

#endif // PLUGIN_MANAGER_GLOBAL_H
